name: fdml-validate
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  validate:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew update-reset
      - run: brew tap ShivsaranshThakur1-Coder/homebrew-fdml
      - run: brew install fdml
      - name: Validate valid corpus (should pass)
        shell: bash
        run: |
          tmp=$(mktemp)
          find corpus/valid -type f -name '*.xml' | sort > "$tmp"
          count=$(wc -l < "$tmp" | tr -d ' ')
          echo "Valid files: $count"
          while IFS= read -r f; do
            echo "::group::valid $f"
            fdml validate "$f"
            echo "::endgroup::"
          done < "$tmp"
          rm -f "$tmp"
      - name: Validate invalid corpus (should fail)
        shell: bash
        run: |
          tmp=$(mktemp)
          find corpus/invalid -type f -name '*.xml' | sort > "$tmp"
          count=$(wc -l < "$tmp" | tr -d ' ')
          echo "Invalid files: $count"
          failures=0
          while IFS= read -r f; do
            echo "::group::invalid $f"
            if fdml validate "$f"; then
              echo "EXPECTED FAILURE but got success: $f"
              failures=$((failures+1))
            fi
            echo "::endgroup::"
          done < "$tmp"
          rm -f "$tmp"
          test $failures -eq 0
