name: fdml-validate
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  validate:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew update-reset
      - run: brew tap ShivsaranshThakur1-Coder/homebrew-fdml
      - run: brew install fdml
      - name: Validate valid corpus (should pass)
        shell: bash
        run: |
          mapfile -t files < <(find corpus/valid -type f -name '*.xml' | sort)
          echo "Valid files: ${#files[@]}"
          for f in "${files[@]}"; do
            echo "::group::valid $f"
            fdml validate "$f"
            echo "::endgroup::"
          done
      - name: Validate invalid corpus (should fail)
        shell: bash
        run: |
          mapfile -t files < <(find corpus/invalid -type f -name '*.xml' | sort)
          echo "Invalid files: ${#files[@]}"
          failures=0
          for f in "${files[@]}"; do
            echo "::group::invalid $f"
            if fdml validate "$f"; then
              echo "EXPECTED FAILURE but got success: $f"
              failures=$((failures+1))
            fi
            echo "::endgroup::"
          done
          test $failures -eq 0
