name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build shaded jar
        run: mvn -q -DskipTests package
      - name: Create GitHub Release (attach jar)
        uses: softprops/action-gh-release@v2
        with:
          files: target/fdml-core.jar
