name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build shaded jar and PDFs
        run: |
          mvn -q -DskipTests package
          ./scripts/gen_examples.sh
          cd docs && zip -r ../fdml-pdfs.zip pdfs
      - name: Create GitHub Release (attach artifacts)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/fdml-core.jar
            fdml-pdfs.zip
